theme: jekyll-theme-minimal
title: Brian D. Christman
description: 

[Research](research.md) 

[Professional Materials](pm.md)    

[Teaching Materials](teaching.md)    

[Blog](blog.md)  

[Running](running.md)

