project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Brian D. Christman" 
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: resources.qmd
        text: Professional Materials
      - href: about.qmd
        text: About Me - Professional
      - href: personal.qmd
        text: About Me - Personal
        
  page-footer: 
    left: "Copyright 2023, Brian D. Christman" 
    right: 
      - icon: book
        href: https://substack.com/@bdchristman?utm_source=user-menu
      - icon: twitter 
        href: https://twitter.com/BiostatsBrian

format:
  html:
    theme: litera
    linkcolor: "dodgerblue"
    toc: false
