project:
  type: website
  output-dir: docs

website:
  title: "bdchristman.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: resources.qmd
        text: Resources
      - href: about.qmd
        text: About Me

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true



