---
title: "Reading Tracker"
format: 
  html: 
    self-contained: true
---

On this page you will find the books and papers that I have read for fun and general edification outside of work and school. 

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(reactable)
library(plyr)
library(ggimage)
library(gganimate)
library(scales)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
Data <- read_excel("~/2024 Reading List.xlsx", sheet = "Full List")
Data$`Date Completed` <- as.Date(Data$`Date Completed`)

Tracking <- read_excel("~/2024 Reading List.xlsx", sheet = "Tracker")
Tracking$Date <- as.Date(Tracking$Date)
```

# Books - Learning
```{r,echo=FALSE, include=TRUE}
Learning_Data <- Data %>% filter(Type == "Book - Learning", !is.na(`Date Completed`)) %>% select(-c("Type","Pages Read"))
  
reactable(Learning_Data, defaultPageSize = 5, defaultColDef = colDef(align = "center"), searchable = TRUE, striped = TRUE, highlight = TRUE, bordered = TRUE, theme = reactableTheme(borderColor = "black", stripedColor = "#E6E6FA", highlightColor = "#E0FFFF", cellPadding = "8px 12px"))
```

# Books - Leisure
```{r,echo=FALSE, include=TRUE}
Leisure_Data <- Data %>% filter(Type == "Book - Leisure", !is.na(`Date Completed`)) %>% select(-c("Type","Pages Read"))
  
reactable(Leisure_Data, defaultPageSize = 5, defaultColDef = colDef(align = "center"), searchable = TRUE, striped = TRUE, highlight = TRUE, bordered = TRUE, theme = reactableTheme(borderColor = "black", stripedColor = "#E6E6FA", highlightColor = "#E0FFFF", cellPadding = "8px 12px"))
```

# Papers
```{r,echo=FALSE, include=TRUE}
Paper_Data <- Data %>% filter(Type == "Paper", !is.na(`Date Completed`)) %>% select(-c("Type","Pages Read"))
  
reactable(Paper_Data, defaultPageSize = 5, defaultColDef = colDef(align = "center"), searchable = TRUE, striped = TRUE, highlight = TRUE, bordered = TRUE, theme = reactableTheme(borderColor = "black", stripedColor = "#E6E6FA", highlightColor = "#E0FFFF", cellPadding = "8px 12px"))
```

# How Much Reading?
```{r, warning=FALSE, message=FALSE, echo=FALSE}
Tracking <- Tracking[order(as.Date(Tracking$`Date`, format="%Y/%m/%d")),]

New_Data <- Tracking %>% group_by(`Date`) %>% mutate(Pages_Total = cumsum(`Pages Read`)) %>% top_n(1, Pages_Total)

New_Data$Days <- round(as.numeric(difftime(New_Data$`Date`, "2023-11-27", units = "days")))

p <- ggplot(New_Data, aes(Days, Pages_Total)) + geom_line(size=1.25, color = "#E6E6FA") + geom_point() + xlab("Days Since I Started Reading") + ylab("Total Pages Read") + theme_classic() + theme(legend.position = "none") + transition_reveal(Days)
animate(p, end_pause = 30)
```

